<?php
namespace App\Features\Membership\Actions;
use App\Enums\MembershipApplicationState;
use App\Enums\MembershipDocumentType;
use App\Models\MembershipApplication;
use App\Models\WorkflowStage;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
final class SubmitMembershipApplicationAction
{
    public function execute(MembershipApplication $application): MembershipApplication
    {
        return DB::transaction(function() use($application){ $application=MembershipApplication::query()->whereKey($application->id)->lockForUpdate()->firstOrFail(); if(!$application->isEditable()) throw ValidationException::withMessages(['application'=>'این درخواست در حال حاضر قابل ارسال نیست.']); $application->load(['companyProfile','shareholders','documents']); $p=$application->companyProfile; $errors=[]; if(!$application->intake_company_name)$errors['intake_company_name']='نام اولیه شرکت تکمیل نشده است.'; if(!$application->representative_name)$errors['representative_name']='نام نماینده شرکت تکمیل نشده است.'; if(!$application->representative_mobile)$errors['representative_mobile']='شماره تماس نماینده تکمیل نشده است.'; if(!$p)$errors['company_profile']='اطلاعات شرکت تکمیل نشده است.'; else { if(!$p->registered_name)$errors['registered_name']='نام فارسی شرکت تکمیل نشده است.'; if(!$p->company_type)$errors['company_type']='نوع ثبت شرکت مشخص نشده است.'; if(!$p->registration_date)$errors['registration_date']='تاریخ ثبت شرکت تکمیل نشده است.'; if(!$p->registration_number)$errors['registration_number']='شماره ثبت شرکت تکمیل نشده است.'; if(!$p->registration_place)$errors['registration_place']='محل ثبت شرکت تکمیل نشده است.'; if($p->registered_capital_irr===null)$errors['registered_capital_irr']='سرمایه ثبت‌شده تکمیل نشده است.'; if(!$p->reference_gazette_date)$errors['reference_gazette_date']='تاریخ روزنامه رسمی تکمیل نشده است.'; if($p->activity_experience_years===null)$errors['activity_experience_years']='سابقه فعالیت شرکت تکمیل نشده است.'; if(!$p->oil_gas_petchem_specialty)$errors['oil_gas_petchem_specialty']='نوع تخصص شرکت تکمیل نشده است.'; if($p->is_chamber_member===null)$errors['is_chamber_member']='وضعیت عضویت در اتاق بازرگانی مشخص نشده است.'; }
            if($application->shareholders->isEmpty())$errors['shareholders']='حداقل یک سهامدار باید ثبت شده باشد.'; else { $total=$application->shareholders->sum(fn($s)=>(float)$s->ownership_percentage); if(abs($total-100)>0.01)$errors['shareholders']='مجموع سهام سهامداران باید دقیقاً ۱۰۰ درصد باشد.'; }
            $types=$application->documents->map(fn($d)=>$d->type instanceof MembershipDocumentType?$d->type->value:$d->type)->all(); $required=[MembershipDocumentType::OfficialGazette,MembershipDocumentType::LatestGeneralAssemblyMinutes,MembershipDocumentType::LatestCapitalGazette,MembershipDocumentType::OriginalCertificate,MembershipDocumentType::CompanyResume]; foreach($required as $t) if(!in_array($t->value,$types,true)) $errors['document_'.$t->value]=sprintf('مدرک «%s» بارگذاری نشده است.',$t->label()); if($p?->is_chamber_member===true && !in_array(MembershipDocumentType::ChamberMembershipCard->value,$types,true)) $errors['chamber_membership_card']='کارت عضویت اتاق بازرگانی بارگذاری نشده است.'; if($errors) throw ValidationException::withMessages($errors); $stage=WorkflowStage::query()->active()->ordered()->first(); if(!$stage) throw ValidationException::withMessages(['application'=>'مراحل بررسی درخواست در سامانه تنظیم نشده است.']); $application->update(['state'=>MembershipApplicationState::InReview,'current_stage_id'=>$stage->id,'return_stage_id'=>null,'submitted_at'=>now(),'approved_at'=>null,'rejected_at'=>null]); return $application->fresh()->load('currentStage'); });
    }
}
